In [ ]:
import pandas as pd

In [ ]:
df1=pd.read_csv('/content/Coursera.csv')
df2=pd.read_csv('/content/Udemy.csv')
df3=pd.read_csv('/content/edx.csv')
df4=pd.read_csv('/content/skillshare.csv')

In [ ]:
df1.head(20)

,partner,course,skills,rating,reviewcount,level,certificatetype,duration,crediteligibility
0,Google,Google Cybersecurity,"{"" Network Security"","" Python Programming"","" L...",4.8,16.4k,Beginner,Professional Certificate,3 - 6 Months,False
1,Google,Google Data Analytics,"{"" Data Analysis"","" R Programming"","" SQL"","" Bu...",4.8,133.4k,Beginner,Professional Certificate,3 - 6 Months,True
2,Google,Google Project Management:,"{"" Project Management"","" Strategy and Operatio...",4.8,97.3k,Beginner,Professional Certificate,3 - 6 Months,True
3,Google,Google Digital Marketing & E-commerce,"{"" Digital Marketing"","" Marketing"","" Marketing...",4.8,21.4k,Beginner,Professional Certificate,3 - 6 Months,False
4,Google,Google IT Support,"{"" Computer Networking"","" Network Architecture...",4.8,181.4k,Beginner,Professional Certificate,3 - 6 Months,True
5,IBM,IBM Data Science,"{"" Python Programming"","" Data Science"","" Machi...",4.6,118.9k,Beginner,Professional Certificate,3 - 6 Months,True
6,Google,Google UX Design,"{"" User Experience"","" User Experience Design"",...",4.8,73.7k,Beginner,Professional Certificate,3 - 6 Months,True
7,IBM,IBM Data Analyst,"{"" Python Programming"","" Data Visualization"",""...",4.6,71.5k,Beginner,Professional Certificate,3 - 6 Months,True
8,Multiple educators,Machine Learning,"{"" Machine Learning"","" Machine Learning Algori...",4.9,17.7k,Beginner,Specialization,1 - 3 Months,False
9,IBM,Introduction to Data Science,"{"" Data Science"","" Python Programming"","" Data ...",4.6,85k,Beginner,Specialization,3 - 6 Months,True
10,DeepLearning.AI,Generative AI for Everyone,"{"" Strategy"","" Writing""}",4.9,188,Beginner,Course,1 - 4 Weeks,False
11,IBM,IBM DevOps and Software Engineering,"{"" DevOps"","" Software Engineering"","" Cloud Com...",4.6,43.2k,Beginner,Professional Certificate,3 - 6 Months,False
12,IBM,IBM Full Stack Software Developer,"{"" Cloud Computing"","" Python Programming"","" Cl...",4.6,41.2k,Beginner,Professional Certificate,3 - 6 Months,True
13,IBM,Key Technologies for Business,"{"" Algorithms"","" Applied Machine Learning"","" A...",4.7,81.5k,Beginner,Specialization,1 - 3 Months,False
14,IBM,Data Science Fundamentals with Python and SQL,"{"" Python Programming"","" Data Analysis"","" Gene...",4.6,59.2k,Beginner,Specialization,3 - 6 Months,True
15,University of Virginia Darden School Foundation,IBM & Darden Digital Strategy,"{"" Business Analysis"","" Business Transformatio...",4.7,29.7k,Beginner,Specialization,3 - 6 Months,False
16,IBM,IBM Data Engineering,"{"" Data Management"","" Databases"","" Database Ad...",4.6,46.2k,Beginner,Professional Certificate,3 - 6 Months,True
17,IBM,IBM Data Analytics with Excel and R,"{"" Data Analysis"","" R Programming"","" Computer ...",4.7,19.9k,Beginner,Professional Certificate,3 - 6 Months,True
18,IBM,Data Analysis and Visualization Foundations,"{"" Microsoft Excel"","" Spreadsheet Software"","" ...",4.7,19.3k,Beginner,Specialization,3 - 6 Months,True
19,DeepLearning.AI,Deep Learning,"{"" Machine Learning"","" Deep Learning"","" Artifi...",4.8,141.5k,Intermediate,Specialization,3 - 6 Months,True

In [ ]:
df1=df1.dropna()

In [ ]:
df1['certificatetype'].value_counts()

certificatetype
Course                       494
Specialization               390
Professional Certificate     100
Guided Project                 9
Name: count, dtype: int64

In [ ]:
df1.head()

,partner,course,skills,rating,reviewcount,level,certificatetype,duration,crediteligibility
0,Google,Google Cybersecurity,"{"" Network Security"","" Python Programming"","" L...",4.8,16.4k,Beginner,Professional Certificate,3 - 6 Months,False
1,Google,Google Data Analytics,"{"" Data Analysis"","" R Programming"","" SQL"","" Bu...",4.8,133.4k,Beginner,Professional Certificate,3 - 6 Months,True
2,Google,Google Project Management:,"{"" Project Management"","" Strategy and Operatio...",4.8,97.3k,Beginner,Professional Certificate,3 - 6 Months,True
3,Google,Google Digital Marketing & E-commerce,"{"" Digital Marketing"","" Marketing"","" Marketing...",4.8,21.4k,Beginner,Professional Certificate,3 - 6 Months,False
4,Google,Google IT Support,"{"" Computer Networking"","" Network Architecture...",4.8,181.4k,Beginner,Professional Certificate,3 - 6 Months,True

In [ ]:
def create_url(row):
  a=row['course'].lower().split()
  aa=("-").join(a)
  if row['certificatetype'] in ['Professional Certificate','Specialization']:
    return "https://www.coursera.org/"+('-').join(row['certificatetype'].lower().split())+"/"+aa
  elif row['certificatetype']=='Course':
    return "https://www.coursera.org/"+"learn"+"/"+aa
  else:
    return "https://www.coursera.org/"+"project"+"/"+aa

# print(create_url({'certificatetype':'Professional Certificate', 'course':'google Cyberseceuty'}))

In [ ]:
df1['course_url']=df1.apply(create_url,axis=1)

In [ ]:
df1=df1.drop(['skills','certificatetype','duration'],axis=1)

In [ ]:
df1.head()

,partner,course,rating,reviewcount,level,crediteligibility,course_url
0,Google,Google Cybersecurity,4.8,16.4k,Beginner,False,https://www.coursera.org/project/google-cybers...
1,Google,Google Data Analytics,4.8,133.4k,Beginner,True,https://www.coursera.org/project/google-data-a...
2,Google,Google Project Management:,4.8,97.3k,Beginner,True,https://www.coursera.org/project/google-projec...
3,Google,Google Digital Marketing & E-commerce,4.8,21.4k,Beginner,False,https://www.coursera.org/project/google-digita...
4,Google,Google IT Support,4.8,181.4k,Beginner,True,https://www.coursera.org/project/google-it-sup...

In [ ]:
type(df1['reviewcount'][0])

str

In [ ]:
def new_rating(a):
  try:
    aa=float(a[:-1].strip())
    if aa>0 and aa<15:
      return 1
    elif aa>=15.0 and aa<35:
      return 2
    elif aa>=35.0 and aa<50.0:
      return 3
    elif aa>=50.0 and aa<100.0:
      return 4
    else:
      return 5
  except:
    return 1


df1['rating_count']=df1['reviewcount'].apply(new_rating)

In [ ]:
df1.head()

,partner,course,rating,reviewcount,level,crediteligibility,course_url,rating_count
0,Google,Google Cybersecurity,4.8,16.4k,Beginner,False,https://www.coursera.org/project/google-cybers...,2
1,Google,Google Data Analytics,4.8,133.4k,Beginner,True,https://www.coursera.org/project/google-data-a...,5
2,Google,Google Project Management:,4.8,97.3k,Beginner,True,https://www.coursera.org/project/google-projec...,4
3,Google,Google Digital Marketing & E-commerce,4.8,21.4k,Beginner,False,https://www.coursera.org/project/google-digita...,2
4,Google,Google IT Support,4.8,181.4k,Beginner,True,https://www.coursera.org/project/google-it-sup...,5

In [ ]:
df1[df1['rating']==5.0]

,partner,course,rating,reviewcount,level,crediteligibility,course_url,rating_count
509,University of Michigan,Using Public Policy for Social Change,5.0,6,Beginner,False,https://www.coursera.org/project/using-public-...,1
865,"Parsons School of Design, The New School",Healthier Materials and Sustainable Building,5.0,10,Intermediate,False,https://www.coursera.org/project/healthier-mat...,1
954,University of Colorado Boulder,Introduction to Systems Engineering,5.0,17,Beginner,False,https://www.coursera.org/project/introduction-...,1

In [ ]:
df1['additional_rating']= df1['crediteligibility'].apply(lambda x :0.1 if x==True else 0)

In [ ]:
df1.head()

,partner,course,rating,reviewcount,level,crediteligibility,course_url,rating_count,additional_rating,final_rating
0,Google,Google Cybersecurity,4.8,16.4k,Beginner,False,https://www.coursera.org/project/google-cybers...,2,0.0,3.53
1,Google,Google Data Analytics,4.8,133.4k,Beginner,True,https://www.coursera.org/project/google-data-a...,5,0.1,4.43
2,Google,Google Project Management:,4.8,97.3k,Beginner,True,https://www.coursera.org/project/google-projec...,4,0.1,4.13
3,Google,Google Digital Marketing & E-commerce,4.8,21.4k,Beginner,False,https://www.coursera.org/project/google-digita...,2,0.0,3.53
4,Google,Google IT Support,4.8,181.4k,Beginner,True,https://www.coursera.org/project/google-it-sup...,5,0.1,4.43

In [ ]:
df1['final_rating'] = df1['rating']*0.7+df1['rating_count']*0.2+df1['additional_rating']*0.5

In [ ]:
df1.head()

,partner,course,rating,reviewcount,level,crediteligibility,course_url,rating_count,additional_rating,final_rating
0,Google,Google Cybersecurity,4.8,16.4k,Beginner,False,https://www.coursera.org/project/google-cybers...,2,0.0,3.76
1,Google,Google Data Analytics,4.8,133.4k,Beginner,True,https://www.coursera.org/project/google-data-a...,5,0.1,4.41
2,Google,Google Project Management:,4.8,97.3k,Beginner,True,https://www.coursera.org/project/google-projec...,4,0.1,4.21
3,Google,Google Digital Marketing & E-commerce,4.8,21.4k,Beginner,False,https://www.coursera.org/project/google-digita...,2,0.0,3.76
4,Google,Google IT Support,4.8,181.4k,Beginner,True,https://www.coursera.org/project/google-it-sup...,5,0.1,4.41

In [ ]:
df1=df1.drop(['rating','reviewcount','level','crediteligibility','rating_count','additional_rating'],axis=1)

In [ ]:
df=pd.read_csv('/content/recommend_course.csv')

In [ ]:
df.head()

,course_id,name,institution,course_url,avg_rating
0,machine-learning,Machine Learning,Stanford University,https://www.coursera.org/learn/machine-learning,4.7
1,indigenous-canada,Indigenous Canada,University of Alberta,https://www.coursera.org/learn/indigenous-canada,4.6
2,the-science-of-well-being,The Science of Well-Being,Yale University,https://www.coursera.org/learn/the-science-of-...,4.7
3,technical-support-fundamentals,Technical Support Fundamentals,Google,https://www.coursera.org/learn/technical-suppo...,4.5
4,google-cbrs-cpi-training,Become a CBRS Certified Professional Installer...,Google - Spectrum Sharing,https://www.coursera.org/learn/google-cbrs-cpi...,4.5

In [ ]:
df.shape

(604, 5)

In [ ]:
df1.shape

(993, 5)

In [ ]:
def id(a):
  return ("-").join(a.lower().split())
df1['course_id']=df1['course'].apply(id)

In [ ]:
df1.head()

,partner,course,course_url,final_rating,course_id
0,Google,Google Cybersecurity,https://www.coursera.org/project/google-cybers...,3.76,google-cybersecurity
1,Google,Google Data Analytics,https://www.coursera.org/project/google-data-a...,4.41,google-data-analytics
2,Google,Google Project Management:,https://www.coursera.org/project/google-projec...,4.21,google-project-management:
3,Google,Google Digital Marketing & E-commerce,https://www.coursera.org/project/google-digita...,3.76,google-digital-marketing-&-e-commerce
4,Google,Google IT Support,https://www.coursera.org/project/google-it-sup...,4.41,google-it-support

In [ ]:
df1=df1.rename(columns={'final_rating':'avg_rating','partner':'institution','course':'name'})

In [ ]:
df_new=pd.concat([df,df1],ignore_index=True)

In [ ]:
df_new.shape

(1597, 5)

In [ ]:
df_new.to_csv('recommend_course1.csv')

In [ ]:
df_new.shape

(1597, 5)

In [ ]:
df_new.isnull().sum()

course_id      0
name           0
institution    0
course_url     0
avg_rating     0
dtype: int64

In [ ]:
df4.head()

,title,link,duration,instructor,students
0,Fundamentals of DSLR Photography,https://www.skillshare.com/en/classes/Fundamen...,1h 19m,Photo Essentials x Justin Bridges,"133,422 students"
1,Video Editing with Adobe Premiere Pro for Begi...,https://www.skillshare.com/en/classes/Video-Ed...,3h 21m,Jordy Vandeput,"126,674 students"
2,Productivity Masterclass - Principles and Tool...,https://www.skillshare.com/en/classes/Producti...,1h 55m,Ali Abdaal,"109,681 students"
3,Adobe Photoshop CC – Essentials Training Course,https://www.skillshare.com/en/classes/Adobe-Ph...,9h 56m,Daniel Scott,"98,746 students"
4,Mastering Productivity: Create a Custom System...,https://www.skillshare.com/en/classes/Masterin...,1h 5m,Thomas Frank,"149,648 students"